apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    app: db
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-sc
  resources: 
    requests:
      storage: 4Gi